project = "egfr"

libinvent-prior = "~/work/ML/REINVENT/REINVENT4/priors/libinvent.prior"
reference-pose = "../input/egfr-ligands-docked.maegz"
reference-mcs = "c1nc(N[*:0])c2cc(-c3ccc([*:1])cc3)[nH]c2n1"
dock-grid = "../input/egfr-grid.zip"
out-dir = "../output/egfr"

sample-size = 3000
target-count = 1000
max-iteration = 20
host = "t41-cpu:128"

tail-timeout = 300

elite-tl-epochs = 3
gbsa-input-count = 50
gbsa-elite-count = 10

ligprep-ph = 7.4
ligprep-pht = 1.0
ligprep-max-states = 2
ligprep-max-stereo = 1

fep-enabled = false
fep-input-count = 10
